version: "3.8"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Panorama2025
      MYSQL_DATABASE: zadex
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: Panorama2025
    ports:
      - "8083:80"
    depends_on:
      - mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: zadex
      DB_USER: root
      DB_PASS: Panorama2025
      DB_PORT: 3306
      DB_CHARSET: utf8mb4
    ports:
      - "8081:80"
    volumes:
      - ./api:/var/www/html/api
      - ./.env:/var/www/html/.env

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    depends_on:
      - backend
    ports:
      - "8082:80"
    environment:
      VITE_API_BASE_URL: http://localhost:8081/backend/api

volumes:
  mysql_data:
